name: Publish to Marketplace

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Extract commit message to workflow env
        run: |
          echo "COMMIT_MESSAGE=$(git log -n 1 --oneline | cut -d' ' -f2- -)" >> $GITHUB_ENV

      - name: Install dependencies
        shell: bash
        run: |
          npm install
        if: ${{ (startsWith(env.COMMIT_MESSAGE, '[Release]') || startsWith(env.COMMIT_MESSAGE, 'Release') || startsWith(env.COMMIT_MESSAGE, '[Publish]')) }}

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
        if: ${{ (startsWith(env.COMMIT_MESSAGE, '[Release]') || startsWith(env.COMMIT_MESSAGE, 'Release') || startsWith(env.COMMIT_MESSAGE, '[Publish]')) }}

      - name: Create git tag
        shell: bash
        run: |
          sudo apt-get install jq
          TAG="$(jq -r .version package.json)"
          git tag "v$TAG"
          git push origin --tags
        if: ${{ (startsWith(env.COMMIT_MESSAGE, '[Release]') || startsWith(env.COMMIT_MESSAGE, 'Release') || startsWith(env.COMMIT_MESSAGE, '[Publish]')) }}
